resources:
  repositories:
  - repository: UDP
    type: github
    endpoint: devopsnights
    name: devopsnights/UDP

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

jobs:

- job: 
  steps:
    - checkout: UDP

- template: template.yml
